# Generated by Django 6.0 on 2025-12-22 17:15

import django.db.models.deletion
import market.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EWasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=market.models.product_image_path)),
                ('weight_kg', models.FloatField(help_text='Approximate weight in KG')),
                ('pickup_pincode', models.CharField(max_length=6)),
                ('listing_type', models.CharField(choices=[('FIXED', 'Fixed Price'), ('AUCTION', 'Auction')], default='FIXED', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyout_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auction_end_time', models.DateTimeField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
