# Generated by Django 6.0 on 2025-12-22 17:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclerprofile',
            name='registration_doc',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.recycler_doc_path),
        ),
    ]
